/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 95802803ff932b62720bd1b44dd9e970)
interface __BaseEnv_Env {
	DB: D1Database;
	ACCESS_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
