/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4427e4d19ecb5cc4cb18a9cfb28ee11e)
interface __BaseEnv_Env {
	DB: D1Database;
	ACCESS_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
